import streamlit as st
from utils.groq_analyzer import analyze_report_with_groq

def render_step4():
    st.subheader("Step 4: Intake AI Audit")
    st.write("Paste the raw Markdown report generated by the AI below.")
    
    report = st.text_area("Paste your AI Audit Report here:", height=300)
    
    col1, col2 = st.columns([1, 4])
    with col1:
        if st.button("Back"):
            st.session_state["step"] = 3
            st.rerun()
    with col2:
        if st.button("Analyze Report"):
            if report.strip() == "":
                st.error("Please paste the report before continuing.")
            else:
                st.session_state["pasted_report"] = report
                
                # Show spinner while Groq works
                with st.spinner("🧠 Groq AI is analyzing your report & routing tactical prompts..."):
                    groq_analysis = analyze_report_with_groq(report)
                    
                if "error" in groq_analysis:
                    st.error(f"Groq API Error: {groq_analysis['error']}")
                else:
                    st.session_state["groq_analysis"] = groq_analysis
                    st.session_state["step"] = 5
                    st.rerun()